name: ci-pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display content
        run: |
          ls -la
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Tests passed!"
